dist: jammy
language: python
python: "3.11"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
services:
  - docker
env:
  global:
    - TIMESTAMP=$(date '+%Y%m%d%H%M%S')
    - CONTAINER=web
    - APPLICATION_NAME=digitized_image_qc
    - APPLICATION_PORT=80

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose up -d

install:
  - pip install pre-commit && pre-commit install
  - ./wait-for-it.sh $CONTAINER:$APPLICATION_PORT -- docker-compose exec $CONTAINER pip install coverage

script:
  - pre-commit run --all-files --show-diff-on-failure
  - docker-compose exec $CONTAINER coverage run manage.py test

after_script:
  - docker-compose exec $CONTAINER coverage report --omit=*/migrations/* -m

before_deploy:
  - pip install awscli
  - docker build -t ${APPLICATION_NAME} --target build .
  - if [ ! -d deploy_scripts ]; then git clone https://github.com/RockefellerArchiveCenter/deploy_scripts.git; fi
deploy:
  - provider: script
    script: >-
      bash deploy_scripts/containers/push_image_to_ecr.sh $APPLICATION_NAME
    on:
      branch: development
  - provider: script
    script: >-
      bash deploy_scripts/containers/add_tag_to_image.sh $APPLICATION_NAME dev prod
    on:
      branch: base

notifications:
  email: false
