# Generated by Django 4.2.4 on 2023-09-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('av_number', models.CharField(max_length=255)),
                ('duration_access', models.FloatField()),
                ('duration_master', models.FloatField()),
                ('multiple_masters', models.BooleanField()),
                ('refid', models.CharField(max_length=32)),
                ('type', models.IntegerField(choices=[(1, 'Audio'), (2, 'Video')])),
                ('process_status', models.IntegerField(choices=[(0, 'Pending'), (9, 'Approved'), (5, 'Rejected')])),
                ('rights_ids', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('aquila_id', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
