# Generated by Django 4.2.5 on 2023-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='possible_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
