# Generated by Django 4.2.5 on 2024-03-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0003_package_resource_title_package_resource_uri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='av_number',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_access',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_master',
        ),
        migrations.RemoveField(
            model_name='package',
            name='multiple_masters',
        ),
        migrations.RemoveField(
            model_name='package',
            name='type',
        ),
        migrations.AddField(
            model_name='package',
            name='tree',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
