# Generated by Django 5.0.4 on 2024-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0004_remove_package_av_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='undated_object',
            field=models.BooleanField(default=False),
        ),
    ]
