# Generated by Django 5.1.4 on 2025-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0006_rename_possible_duplicate_package_already_digitized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='process_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (9, 'Approved'), (5, 'Rejected'), (10, 'Delivered')]),
        ),
    ]
