# Generated by Django 5.1.4 on 2025-01-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    def update_status(apps, schema_editor):
        Package = apps.get_model("package_review", "Package")
        for package in Package.objects.filter(process_status=9):
            package.process_status = 10
            package.save()

    def reset_status(apps, schema_editor):
        Package = apps.get_model("package_review", "Package")
        for package in Package.objects.filter(process_status=10):
            package.process_status = 9
            package.save()

    dependencies = [
        ('package_review', '0007_alter_package_process_status'),
    ]

    operations = [
        migrations.RunPython(update_status, reset_status),
    ]
