# Generated by Django 5.1.4 on 2025-01-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    def remove_tree(apps, schema_editor):
        Package = apps.get_model("package_review", "Package")
        for package in Package.objects.all():
            package.tree = None
            package.save()

    dependencies = [
        ('package_review', '0009_auto_20250127_2112'),
    ]

    operations = [
        migrations.RunPython(remove_tree),
    ]
