# Generated by Django 5.2.3 on 2025-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0011_package_created_at_package_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='process_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (9, 'Approved'), (5, 'Rejected')]),
        ),
    ]
