# Generated by Django 5.2.6 on 2025-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0012_alter_package_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
