# Generated by Django 5.2.7 on 2025-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0013_package_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='reel_box',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
