# Generated by Django 5.2.7 on 2025-11-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0014_package_reel_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='reel_box',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
