# Generated by Django 5.2.7 on 2025-11-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0015_alter_package_reel_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='reel_box',
            field=models.TextField(blank=True, null=True),
        ),
    ]
