# Generated by Django 5.2.10 on 2026-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0016_alter_package_reel_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
