# Generated by Django 5.2.15 on 2026-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0017_package_package_id_package_source_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
