Header set Accept-Ranges bytes

<VirtualHost *:${APPLICATION_PORT}>
    ServerName ${APPLICATION_NAME}
    DocumentRoot /var/www/${APPLICATION_NAME}/
    ErrorLog /dev/stdout
    Alias /static /var/www/${APPLICATION_NAME}/static
    <Directory /var/www/${APPLICATION_NAME}/static>
        Require all granted
    </Directory>
    <Directory /var/www/${APPLICATION_NAME}/${APPLICATION_DIR}>
        WSGIProcessGroup ${APPLICATION_NAME}
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>
    WSGIDaemonProcess ${APPLICATION_NAME} home=/var/www/${APPLICATION_NAME}
    WSGIProcessGroup ${APPLICATION_NAME}
    WSGIScriptAlias / /var/www/${APPLICATION_NAME}/${APPLICATION_DIR}/wsgi.py
</VirtualHost>